PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS agencies (id INTEGER PRIMARY KEY, name TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, email TEXT NOT NULL UNIQUE COLLATE NOCASE, display_name TEXT NOT NULL, password_hash TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS agency_memberships (id INTEGER PRIMARY KEY, agency_id INTEGER NOT NULL REFERENCES agencies(id) ON DELETE CASCADE, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, role TEXT NOT NULL CHECK(role IN ('agency_admin','agency_member')), active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)), UNIQUE(agency_id,user_id));
CREATE TABLE IF NOT EXISTS clients (id INTEGER PRIMARY KEY, agency_id INTEGER NOT NULL REFERENCES agencies(id) ON DELETE CASCADE, name TEXT NOT NULL, UNIQUE(agency_id,name));
CREATE TABLE IF NOT EXISTS client_contacts (id INTEGER PRIMARY KEY, client_id INTEGER NOT NULL REFERENCES clients(id) ON DELETE CASCADE, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)), UNIQUE(client_id,user_id));
CREATE TABLE IF NOT EXISTS projects (id INTEGER PRIMARY KEY, agency_id INTEGER NOT NULL REFERENCES agencies(id) ON DELETE CASCADE, client_id INTEGER NOT NULL REFERENCES clients(id) ON DELETE RESTRICT, name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', UNIQUE(agency_id,name));
CREATE TABLE IF NOT EXISTS project_members (project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE, membership_id INTEGER NOT NULL REFERENCES agency_memberships(id) ON DELETE CASCADE, PRIMARY KEY(project_id,membership_id));
CREATE TABLE IF NOT EXISTS tasks (id INTEGER PRIMARY KEY, agency_id INTEGER NOT NULL REFERENCES agencies(id) ON DELETE CASCADE, project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE, title TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'todo' CHECK(status IN ('todo','in_progress','done')), priority TEXT NOT NULL DEFAULT 'medium' CHECK(priority IN ('low','medium','high')), assignee_membership_id INTEGER REFERENCES agency_memberships(id) ON DELETE SET NULL, due_date TEXT, is_client_visible INTEGER NOT NULL DEFAULT 0 CHECK(is_client_visible IN (0,1)), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS comments (id INTEGER PRIMARY KEY, task_id INTEGER NOT NULL REFERENCES tasks(id) ON DELETE CASCADE, author_user_id INTEGER NOT NULL REFERENCES users(id), body TEXT NOT NULL, is_client_visible INTEGER NOT NULL DEFAULT 0 CHECK(is_client_visible IN (0,1)), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS time_entries (id INTEGER PRIMARY KEY, task_id INTEGER NOT NULL REFERENCES tasks(id) ON DELETE CASCADE, membership_id INTEGER NOT NULL REFERENCES agency_memberships(id), minutes INTEGER NOT NULL CHECK(minutes > 0), note TEXT NOT NULL DEFAULT '', entry_date TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS attachments (id INTEGER PRIMARY KEY, task_id INTEGER NOT NULL REFERENCES tasks(id) ON DELETE CASCADE, uploader_user_id INTEGER NOT NULL REFERENCES users(id), filename TEXT NOT NULL, storage_key TEXT NOT NULL, is_client_visible INTEGER NOT NULL DEFAULT 0 CHECK(is_client_visible IN (0,1)), approval_status TEXT NOT NULL DEFAULT 'pending' CHECK(approval_status IN ('pending','approved','needs_changes')), approval_note TEXT NOT NULL DEFAULT '', approved_by_user_id INTEGER REFERENCES users(id), approved_at TEXT);
CREATE TABLE IF NOT EXISTS invites (id INTEGER PRIMARY KEY, agency_id INTEGER NOT NULL REFERENCES agencies(id) ON DELETE CASCADE, email TEXT NOT NULL COLLATE NOCASE, role TEXT NOT NULL CHECK(role IN ('agency_admin','agency_member')), state TEXT NOT NULL DEFAULT 'pending' CHECK(state IN ('pending','accepted','revoked')), token TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, accepted_at TEXT, UNIQUE(agency_id,email));

CREATE TRIGGER IF NOT EXISTS project_client_same_agency BEFORE INSERT ON projects BEGIN SELECT CASE WHEN (SELECT agency_id FROM clients WHERE id=NEW.client_id) != NEW.agency_id THEN RAISE(ABORT,'project client belongs to another agency') END; END;
CREATE TRIGGER IF NOT EXISTS task_project_same_agency BEFORE INSERT ON tasks BEGIN SELECT CASE WHEN (SELECT agency_id FROM projects WHERE id=NEW.project_id) != NEW.agency_id THEN RAISE(ABORT,'task project belongs to another agency') END; END;
CREATE TRIGGER IF NOT EXISTS task_assignee_on_project BEFORE INSERT ON tasks WHEN NEW.assignee_membership_id IS NOT NULL BEGIN SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM project_members pm WHERE pm.project_id=NEW.project_id AND pm.membership_id=NEW.assignee_membership_id) THEN RAISE(ABORT,'assignee is not assigned to project') END; END;
CREATE TRIGGER IF NOT EXISTS task_assignee_on_project_update BEFORE UPDATE OF assignee_membership_id,project_id ON tasks WHEN NEW.assignee_membership_id IS NOT NULL BEGIN SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM project_members pm WHERE pm.project_id=NEW.project_id AND pm.membership_id=NEW.assignee_membership_id) THEN RAISE(ABORT,'assignee is not assigned to project') END; END;
CREATE TRIGGER IF NOT EXISTS project_member_same_agency BEFORE INSERT ON project_members BEGIN SELECT CASE WHEN (SELECT agency_id FROM projects WHERE id=NEW.project_id) != (SELECT agency_id FROM agency_memberships WHERE id=NEW.membership_id) THEN RAISE(ABORT,'project member crosses agency') END; END;
CREATE TRIGGER IF NOT EXISTS time_entry_tenant BEFORE INSERT ON time_entries BEGIN SELECT CASE WHEN (SELECT agency_id FROM agency_memberships WHERE id=NEW.membership_id) != (SELECT agency_id FROM tasks WHERE id=NEW.task_id) THEN RAISE(ABORT,'time entry crosses agency') END; END;
