import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const API=import.meta.env.VITE_API_URL || 'https://sapyon-assignment.onrender.com';
const emptyTask={title:'',description:'',priority:'medium',due_date:'',is_client_visible:true};

function App(){
 const [auth,setAuth]=useState(null),[email,setEmail]=useState('ada@northstar.test'),[password,setPassword]=useState('demo-password');
 const [projects,setProjects]=useState([]),[selected,setSelected]=useState(null),[tasks,setTasks]=useState([]),[dash,setDash]=useState(null),[detail,setDetail]=useState(null),[note,setNote]=useState(''),[profile,setProfile]=useState(null),[taskForm,setTaskForm]=useState(emptyTask),[showCreate,setShowCreate]=useState(false);
 const headers=auth?{Authorization:'Bearer '+auth.token,'Content-Type':'application/json'}:{};
 const request=async(path,options={})=>{const r=await fetch(API+path,{...options,headers:{...headers,...(options.headers||{})}});if(!r.ok){const body=await r.json().catch(()=>({}));throw Error(body.detail||'Request failed')}return r.status===204?null:r.json()};
 const refreshProject=async(p=selected)=>{if(!p)return;setTasks(await request('/projects/'+p.id+'/tasks'));setDash(await request('/projects/'+p.id+'/dashboard'))};
 const open=async p=>{setSelected(p);setDetail(null);setShowCreate(false);await refreshProject(p)};
 const load=async()=>{const [p,me]=await Promise.all([request('/projects'),request('/me')]);setProjects(p);setProfile(me);if(p[0])await open(p[0])};
 const login=async e=>{e.preventDefault();try{const r=await fetch(API+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});if(!r.ok)throw Error();setAuth(await r.json())}catch{alert('Sign-in failed')}};
 useEffect(()=>{if(auth)load().catch(e=>alert(e.message))},[auth]);
 const staffRole=selected&&profile?.staff_agencies.find(a=>a.id===selected.agency_id)?.role; const isStaff=!!staffRole; const isAdmin=staffRole==='agency_admin';
 const show=async id=>{try{setDetail(await request('/tasks/'+id))}catch(e){alert(e.message)}};
 const comment=async()=>{if(!note)return;try{await request('/tasks/'+detail.id+'/comments',{method:'POST',body:JSON.stringify({body:note,is_client_visible:true})});setNote('');await show(detail.id)}catch(e){alert(e.message)}};
 const createTask=async e=>{e.preventDefault();try{await request('/projects/'+selected.id+'/tasks',{method:'POST',body:JSON.stringify({...taskForm,due_date:taskForm.due_date||null})});setTaskForm(emptyTask);setShowCreate(false);await refreshProject()}catch(e){alert(e.message)}};
 const updateStatus=async status=>{try{await request('/tasks/'+detail.id+'/status',{method:'PATCH',body:JSON.stringify({status})});await show(detail.id);await refreshProject()}catch(e){alert(e.message)}};
 const removeTask=async()=>{if(!confirm('Delete this task permanently?'))return;try{await request('/tasks/'+detail.id,{method:'DELETE'});setDetail(null);await refreshProject()}catch(e){alert(e.message)}};
 if(!auth)return <main className="login"><h1>AgencyDesk</h1><p>Agency and client project workspace</p><form onSubmit={login}><input value={email} onChange={e=>setEmail(e.target.value)} aria-label="Email"/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} aria-label="Password"/><button>Sign in</button></form><small>Try sam@acme.test for the client portal.</small></main>;
 return <main><header><div><b>AgencyDesk</b><span>{auth.user.name} · {auth.user.email}</span></div><button onClick={()=>{setAuth(null);setProfile(null)}}>Sign out</button></header><div className="layout"><aside><h3>Projects</h3>{projects.map(p=><button className={selected?.id===p.id?'active':''} onClick={()=>open(p)} key={p.id}>{p.name}</button>)}</aside><section>{selected&&<><h1>{selected.name}</h1><p>{selected.description}</p><div className="metrics"><div><b>{dash?.hours_logged}h</b><small>logged</small></div>{Object.entries(dash?.task_counts||{}).map(([k,v])=><div key={k}><b>{v}</b><small>{k.replace('_',' ')}</small></div>)}</div><div className="section-title"><h2>Tasks</h2>{isStaff&&<button className="primary" onClick={()=>setShowCreate(!showCreate)}>{showCreate?'Cancel':'Create task'}</button>}</div>{showCreate&&<form className="task-form" onSubmit={createTask}><input required placeholder="Task title" value={taskForm.title} onChange={e=>setTaskForm({...taskForm,title:e.target.value})}/><textarea placeholder="Description" value={taskForm.description} onChange={e=>setTaskForm({...taskForm,description:e.target.value})}/><div className="form-row"><select value={taskForm.priority} onChange={e=>setTaskForm({...taskForm,priority:e.target.value})}><option value="low">Low priority</option><option value="medium">Medium priority</option><option value="high">High priority</option></select><input type="date" value={taskForm.due_date} onChange={e=>setTaskForm({...taskForm,due_date:e.target.value})}/></div><label><input type="checkbox" checked={taskForm.is_client_visible} onChange={e=>setTaskForm({...taskForm,is_client_visible:e.target.checked})}/> Visible to client</label><button className="primary">Create task</button></form>}<div className="tasks">{tasks.map(t=><button key={t.id} onClick={()=>show(t.id)}><strong>{t.title}</strong><span>{t.status} · {t.priority} · {t.is_client_visible?'Client visible':'Internal'}</span></button>)}</div></>}</section>{detail&&<aside className="detail"><button onClick={()=>setDetail(null)}>Close</button><h2>{detail.title}</h2><p>{detail.description}</p>{isStaff&&<div className="task-actions"><label>Status<select value={detail.status} onChange={e=>updateStatus(e.target.value)}><option value="todo">To do</option><option value="in_progress">In progress</option><option value="done">Completed</option></select></label>{isAdmin&&<button className="danger" onClick={removeTask}>Delete task</button>}</div>}<h3>Comments</h3>{detail.comments.map(c=><p className="comment" key={c.id}>{c.body}</p>)}<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Add a comment"/><button className="primary" onClick={comment}>Comment</button><h3>Files</h3>{detail.attachments.map(a=><p key={a.id}>{a.filename} — {a.approval_status}</p>)}</aside>}</div></main>}
createRoot(document.getElementById('root')).render(<App/>);
